"""Gating test for the generate-first registry contract (T1.1 #418).

Stdlib-only, runs in the deterministic CI floor (pr-tests.yml). Asserts:
  * the GENERATED files (scripts/features/registry_constants_generated.py +
    data/catalog/obs_spec.generated.json) are FRESH — regenerating from the committed
    registry produces zero diff. Definition drift becomes a build failure.
  * the registry <-> curated-artifact LINKAGE is valid (validate-only, never overwriting the
    curated files): every feature `source:` exists in catalog_schema.sql; every FITTED feature
    has a matching key+method in normalization_stats.template.json; dataset_spec dims match.
  * the refactored consumers (agent_observation, shard_contract) DERIVE their dims from the
    generated module — so the hand-copied dims that used to drift are gone.
  * `_`-prefixed documentation keys can never influence a generated byte.

Modelled on tests/test_golden_vector_parity.py (regenerate -> compare).
"""
import copy
import sys
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts import generate_from_registry as g  # noqa: E402


class TestRegistryGenerate(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.reg = g.load_registry()

    # --- the zero-diff gate -------------------------------------------------
    def test_generated_files_are_fresh(self):
        problems = g.check_generated(self.reg)
        self.assertEqual(
            problems, [],
            "GENERATED files are stale — run `python scripts/generate_from_registry.py` and "
            "commit:\n" + "\n".join(problems))

    def test_drift_would_fail_the_gate(self):
        """A registry change that is NOT regenerated must make the generated file stale."""
        mutated = copy.deepcopy(self.reg)
        mutated["observation"]["self_layout"].append("fake_channel_xyz")
        self.assertNotEqual(
            g.build_constants(mutated), g.CONSTANTS_PY.read_text(encoding="utf-8"),
            "a registry observation change must change the generated constants (the gate must bite)")

    # --- registry <-> curated-artifact linkage (validate-only) --------------
    def test_schema_source_linkage(self):
        self.assertEqual(g.validate_schema_sources(self.reg), [])

    def test_norm_key_linkage(self):
        self.assertEqual(g.validate_norm_keys(self.reg), [])

    def test_dataset_spec_dims_match(self):
        self.assertEqual(g.validate_dataset_spec(self.reg), [])

    # --- _-prefixed docs cannot influence generated output ------------------
    def test_underscore_keys_cannot_influence_output(self):
        stripped = g.strip_underscore(self.reg)
        self.assertEqual(g.build_constants(stripped), g.build_constants(self.reg))
        self.assertEqual(g.build_obs_spec(stripped), g.build_obs_spec(self.reg))

    # --- the observation layout (incl. the onground drift fix) --------------
    def test_observation_layout_sane(self):
        obs = self.reg["observation"]
        self.assertEqual(len(obs["self_layout"]), 21)
        self.assertEqual(len(obs["entity_layout"]), 13)
        self.assertEqual(len(obs["action_layout"]), 5)
        self.assertEqual(obs["self_history"], 16)
        # onground was in the live encoder but UNREGISTERED before this ticket — now both
        # a registered feature AND in the explicit self layout.
        self.assertIn("onground", obs["self_layout"])
        pos = self.reg["feature_groups"]["position"]
        self.assertTrue(any(f.get("name") == "onground" for f in pos),
                        "onground must be a registered feature in feature_groups.position")

    # --- the consumers derive from the generated module (no hand-copied dims) -
    def test_consumers_derive_from_generated(self):
        from scripts.features import registry_constants_generated as rc
        from scripts.features import agent_observation as ao
        from ml.broad_bc import shard_contract as sc
        obs = self.reg["observation"]
        # the generated module mirrors the registry observation block exactly
        self.assertEqual(list(rc.SELF_FIELDS), list(obs["self_layout"]))
        self.assertEqual(list(rc.ENTITY_FIELDS), list(obs["entity_layout"]))
        self.assertEqual(list(rc.ACT_FIELDS), list(obs["action_layout"]))
        self.assertEqual(rc.SELF_DIM, 21)
        self.assertEqual(rc.SELF_HISTORY_DIM, rc.SELF_HISTORY * rc.SELF_DIM)
        self.assertEqual(rc.REGISTRY_VERSION, self.reg["registry_version"])
        # the live encoder IMPORTS the generated constants (same object — no hand-copied dims)
        self.assertIs(ao.SELF_FIELDS, rc.SELF_FIELDS)
        self.assertEqual(ao.SELF_DIM, rc.SELF_DIM)
        self.assertEqual(ao.N_MAX_DEFAULT, rc.N_MAX_DEFAULT)
        # the shard contract derives EXPECTS_* from the SAME generated source
        self.assertEqual(sc.EXPECTS_REGISTRY_VERSION, rc.REGISTRY_VERSION)
        self.assertEqual(sc.EXPECTS_SELF_DIM, rc.SELF_DIM)
        self.assertEqual(sc.EXPECTS_SELF_HISTORY, rc.SELF_HISTORY)
        self.assertEqual(sc.EXPECTS_SELF_HISTORY_DIM, rc.SELF_HISTORY_DIM)
        self.assertEqual(tuple(sc.REQUIRED_NORM_KEYS), tuple(rc.REQUIRED_NORM_KEYS))
        self.assertEqual(sc.DEFAULT_N_MAX, rc.N_MAX_DEFAULT)
        # the cloned action heads cannot drift from the registry action layout
        self.assertEqual(list(sc.ACT_COLS[:5]), list(obs["action_layout"]))


if __name__ == "__main__":
    unittest.main()
