#!/usr/bin/env python3
"""generate_from_registry — the generate-first source-of-truth tool (T1.1 #418).

`data/catalog/feature_registry.json` is the SINGLE declarative source for the model's
inputs. This script DERIVES the artifacts that must never drift from it, and VALIDATES the
curated artifacts that legitimately hold config the registry does not (map geometry, fitted
stats). It is **pure standard library** (no PyYAML / no third-party) so it runs in the
deterministic CI floor (`pr-tests.yml`, Python 3.12).

GENERATED (regenerated from the registry; the CI gate asserts zero-diff on `--check`):
  * scripts/features/registry_constants_generated.py  — SELF_FIELDS / dims / REGISTRY_VERSION
        / REQUIRED_NORM_KEYS imported by the live encoder (agent_observation.py) and the shard
        contract (shard_contract.py) — replacing their hand-copied dims (the silent-drift fix).
  * data/catalog/obs_spec.generated.json              — the obs-vector layout + dims.

VALIDATED (curated files we do NOT overwrite — they own config outside the registry):
  * scripts/catalog_schema.sql            — every feature `source:` "table.column" must exist.
  * data/catalog/normalization_stats.template.json — every FITTED feature (zscore/minmax/robust/
        log1p_zscore with a stats_key) must have a matching key+method (the template keeps the
        verified AABB bounds / provenance; we only check the registry<->template linkage).
  * data/catalog/dataset_spec.yaml        — its registry_version + N_max must match the registry.

CONVENTION: any registry key beginning with `_` is documentation-only and is ignored here.

Usage:
    python scripts/generate_from_registry.py            # regenerate the GENERATED files + validate
    python scripts/generate_from_registry.py --check     # write nothing; assert zero-diff + validate
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path

LOGGER = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_JSON = REPO_ROOT / "data" / "catalog" / "feature_registry.json"
CONSTANTS_PY = REPO_ROOT / "scripts" / "features" / "registry_constants_generated.py"
OBS_SPEC_JSON = REPO_ROOT / "data" / "catalog" / "obs_spec.generated.json"
SCHEMA_SQL = REPO_ROOT / "scripts" / "catalog_schema.sql"
NORM_TEMPLATE = REPO_ROOT / "data" / "catalog" / "normalization_stats.template.json"
DATASET_SPEC = REPO_ROOT / "data" / "catalog" / "dataset_spec.yaml"

# fitted norm methods (need a per-split/per-map fitted stat -> a stats_key + a template entry).
# parameter-free methods (sincos/divide_period/identity) need NO fitted key, so they are not
# checked against the normalization template.
_FITTED_METHODS = {"zscore", "minmax", "robust", "log1p_zscore"}

_GEN_HEADER = (
    "# AUTO-GENERATED — DO NOT HAND-EDIT.\n"
    "# Generated from data/catalog/feature_registry.json by scripts/generate_from_registry.py\n"
    "# Regenerate with: python scripts/generate_from_registry.py\n"
)
_GEN_DOC_JSON = (
    "AUTO-GENERATED from data/catalog/feature_registry.json by "
    "scripts/generate_from_registry.py — DO NOT HAND-EDIT. "
    "Regenerate with: python scripts/generate_from_registry.py"
)


# =============================================================================
# load
# =============================================================================
def load_registry(path: Path = REGISTRY_JSON) -> dict:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def strip_underscore(obj):
    """Recursively drop every dict key beginning with `_` (documentation-only).

    Proves (via the test) that the doc keys can never influence a generated byte:
    generating from strip_underscore(reg) must equal generating from reg.
    """
    if isinstance(obj, dict):
        return {k: strip_underscore(v) for k, v in obj.items() if not str(k).startswith("_")}
    if isinstance(obj, list):
        return [strip_underscore(v) for v in obj]
    return obj


# =============================================================================
# GENERATE: registry_constants_generated.py
# =============================================================================
def _py_tuple(name: str, items) -> str:
    """A deterministic one-string-per-line Python tuple literal."""
    if not items:
        return f"{name} = ()"
    body = "".join(f"    {json.dumps(str(it))},\n" for it in items)
    return f"{name} = (\n{body})"


def build_constants(reg: dict) -> str:
    obs = reg["observation"]
    self_layout = list(obs["self_layout"])
    entity_layout = list(obs["entity_layout"])
    action_layout = list(obs["action_layout"])
    self_history = int(obs["self_history"])
    self_dim = len(self_layout)
    parts = [
        _GEN_HEADER,
        '"""Generated registry constants — the SINGLE source for the obs-vector layout.\n'
        "\n"
        "Imported by scripts/features/agent_observation.py (the live + offline encoder) and\n"
        "ml/broad_bc/shard_contract.py (the shard contract) so the SELF/entity/action layout and\n"
        "the v5 history dims live in ONE place — data/catalog/feature_registry.json `observation`.\n"
        '"""',
        "import logging\n\nLOGGER = logging.getLogger(__name__)",
        f"REGISTRY_VERSION = {int(reg['registry_version'])}",
        _py_tuple("SELF_FIELDS", self_layout),
        f"SELF_DIM = {self_dim}",
        f"SELF_HISTORY = {self_history}",
        f"SELF_HISTORY_DIM = SELF_HISTORY * SELF_DIM  # {self_history * self_dim}",
        _py_tuple("ENTITY_FIELDS", entity_layout),
        f"ENTITY_DIM = {len(entity_layout)}",
        _py_tuple("ACT_FIELDS", action_layout),
        f"ACT_DIM = {len(action_layout)}",
        f"N_MAX_DEFAULT = {int(obs['n_max'])}",
        _py_tuple("REQUIRED_NORM_KEYS", list(obs["required_norm_keys"])),
    ]
    return "\n\n".join(parts) + "\n"


# =============================================================================
# GENERATE: obs_spec.generated.json
# =============================================================================
def build_obs_spec(reg: dict) -> str:
    obs = reg["observation"]
    self_layout = list(obs["self_layout"])
    self_history = int(obs["self_history"])
    spec = {
        "_doc": _GEN_DOC_JSON,
        "schema": "komodobots.obs_spec.v1",
        "registry_version": int(reg["registry_version"]),
        "self_layout": self_layout,
        "self_dim": len(self_layout),
        "self_history": self_history,
        "self_history_dim": self_history * len(self_layout),
        "entity_layout": list(obs["entity_layout"]),
        "entity_dim": len(obs["entity_layout"]),
        "action_layout": list(obs["action_layout"]),
        "action_dim": len(obs["action_layout"]),
        "n_max": int(obs["n_max"]),
        "required_norm_keys": list(obs["required_norm_keys"]),
    }
    return json.dumps(spec, indent=2, ensure_ascii=False) + "\n"


# =============================================================================
# VALIDATE (read-only; the curated files are never overwritten)
# =============================================================================
def _schema_columns(sql_text: str) -> "dict[str, set[str]]":
    """{table: {column,...}} from CREATE TABLE blocks (constraint/comment lines skipped)."""
    tables: "dict[str, set[str]]" = {}
    constraint_kw = ("PRIMARY", "FOREIGN", "UNIQUE", "CHECK", "CONSTRAINT")
    for m in re.finditer(r"CREATE\s+TABLE\s+(\w+)\s*\((.*?)\n\s*\);", sql_text, re.DOTALL | re.IGNORECASE):
        cols: "set[str]" = set()
        for raw in m.group(2).splitlines():
            line = re.split(r"--", raw, 1)[0].strip()
            if not line:
                continue
            for piece in line.split(","):
                piece = piece.strip()
                if not piece:
                    continue
                tok = piece.split()[0]
                if tok.upper() in constraint_kw:
                    break
                if re.match(r"^[A-Za-z_]\w*$", tok):
                    cols.add(tok)
        tables[m.group(1)] = cols
    return tables


def registry_source_refs(reg: dict) -> "dict[str, set[str]]":
    """{`table.column`: {feature names}} pulled from each feature `source:` (dotted tokens only)."""
    refs: "dict[str, set[str]]" = {}
    for _group, feats in reg.get("feature_groups", {}).items():
        for fe in feats:
            if not isinstance(fe, dict):
                continue
            name = str(fe.get("name", "?"))
            for tok in re.findall(r"\b([A-Za-z_][A-Za-z0-9_]*\.[A-Za-z0-9_]+)\b", str(fe.get("source", ""))):
                refs.setdefault(tok, set()).add(name)
    return refs


def validate_schema_sources(reg: dict, schema_path: Path = SCHEMA_SQL) -> "list[str]":
    """Every feature `source:` 'table.column' must exist in catalog_schema.sql. Returns problems."""
    schema = _schema_columns(Path(schema_path).read_text(encoding="utf-8"))
    problems: "list[str]" = []
    for ref, feats in sorted(registry_source_refs(reg).items()):
        table, col = ref.split(".", 1)
        if table not in schema:
            problems.append(f"source {ref} -> unknown table (features: {sorted(feats)})")
        elif col not in schema[table]:
            problems.append(f"source {ref} -> unknown column (features: {sorted(feats)})")
    return problems


def validate_norm_keys(reg: dict, norm_path: Path = NORM_TEMPLATE, *, canonical_map: str = "dm3") -> "list[str]":
    """Every FITTED feature's stats_key must resolve to a matching key+method in the norm template.

    stats_key is `per_map.<map>.X` (checked against per_map[canonical_map][X]) or `global.X`
    (checked against global[X]). Parameter-free features (no stats_key / non-fitted method) skip.
    The template is NOT modified — only the registry<->template linkage is asserted.
    """
    stats = json.loads(Path(norm_path).read_text(encoding="utf-8"))
    per_map = (stats.get("per_map") or {}).get(canonical_map, {})
    glob = stats.get("global") or {}
    problems: "list[str]" = []
    for _group, feats in reg.get("feature_groups", {}).items():
        for fe in feats:
            if not isinstance(fe, dict):
                continue
            method = fe.get("norm")
            stats_key = fe.get("stats_key")
            if method not in _FITTED_METHODS or not stats_key:
                continue
            parts = str(stats_key).split(".")
            if parts[0] == "per_map" and len(parts) == 3:
                key, table = parts[2], per_map
            elif parts[0] == "global" and len(parts) == 2:
                key, table = parts[1], glob
            else:
                problems.append(f"{fe.get('name')}: unparseable stats_key {stats_key!r}")
                continue
            entry = table.get(key)
            if entry is None:
                problems.append(f"{fe.get('name')}: stats_key {stats_key!r} missing from normalization template")
            elif entry.get("method") != method:
                problems.append(
                    f"{fe.get('name')}: norm method {method!r} != template method "
                    f"{entry.get('method')!r} for {stats_key!r}")
    return problems


def _scan_dataset_spec(spec_path: Path) -> "dict[str, int]":
    """Minimal stdlib read of registry_version (top-level) + N_max (under entity_max:)."""
    out: "dict[str, int]" = {}
    section = ""
    for raw in Path(spec_path).read_text(encoding="utf-8").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        m = re.match(r"^([A-Za-z_]\w*)\s*:\s*(.*)$", raw.strip())
        if not m:
            continue
        key, val = m.group(1), m.group(2).split("#", 1)[0].strip()
        if indent == 0:
            section = key
            if key == "registry_version" and val:
                out["registry_version"] = int(val)
        elif section == "entity_max" and key == "N_max" and val:
            out["N_max"] = int(val)
    return out


def validate_dataset_spec(reg: dict, spec_path: Path = DATASET_SPEC) -> "list[str]":
    """dataset_spec.yaml registry_version + entity_max.N_max must match the registry."""
    ds = _scan_dataset_spec(spec_path)
    problems: "list[str]" = []
    rv = int(reg["registry_version"])
    if ds.get("registry_version") != rv:
        problems.append(f"dataset_spec registry_version {ds.get('registry_version')} != registry {rv}")
    n_max = int(reg["observation"]["n_max"])
    if ds.get("N_max") != n_max:
        problems.append(f"dataset_spec entity_max.N_max {ds.get('N_max')} != observation.n_max {n_max}")
    return problems


# fitted-method set lives above; sincos channels flatten <base>_sincos -> <base>_sin/<base>_cos.
_SINCOS_SUFFIXES = ("_sin", "_cos")


def _registered_feature_names(reg: dict) -> "set[str]":
    """Every feature `name` declared across feature_groups (doc-only `_` groups skipped)."""
    names: "set[str]" = set()
    for group, feats in reg.get("feature_groups", {}).items():
        if str(group).startswith("_"):
            continue
        for fe in feats:
            if isinstance(fe, dict) and "name" in fe:
                names.add(str(fe["name"]))
    return names


def _sincos_bases(reg: dict) -> "set[str]":
    """Names of features whose `norm` is sincos (each flattens to <name minus _sincos>_sin/_cos)."""
    bases: "set[str]" = set()
    for group, feats in reg.get("feature_groups", {}).items():
        if str(group).startswith("_"):
            continue
        for fe in feats:
            if isinstance(fe, dict) and fe.get("norm") == "sincos":
                bases.add(str(fe.get("name", "")))
    return bases


def validate_layout_channel_coverage(reg: dict) -> "list[str]":
    """Every flattened obs-layout channel must resolve to a REGISTERED feature (fail-closed).

    A channel `ch` resolves iff (a) `ch` is itself a registered feature name, or (b) `ch` is the
    documented sincos flattening `<base>_sin` / `<base>_cos` of a feature registered as
    `<base>_sincos` with `norm: sincos`. Anything else is a model input that is emitted into
    SELF/ENTITY/ACT_FIELDS + obs_spec but never declared/source-validated in the registry — the
    exact silent-drift class T1.1 exists to eliminate (cf. `onground`, `entity_alive`) — so it
    fails the build instead of passing while undocumented.
    """
    names = _registered_feature_names(reg)
    sincos = _sincos_bases(reg)
    obs = reg.get("observation", {})
    problems: "list[str]" = []
    for layout in ("self_layout", "entity_layout", "action_layout"):
        for ch in obs.get(layout, []):
            if ch in names:
                continue
            if ch.endswith(_SINCOS_SUFFIXES) and (ch[:-4] + "_sincos") in sincos:
                continue
            problems.append(
                f"{layout} channel {ch!r} resolves to no registered feature "
                f"(declare it in feature_groups, or register a `{ch[:-4]}_sincos` sincos feature)")
    return problems


# =============================================================================
# emit / check / validate-all
# =============================================================================
def _targets(reg: dict) -> "list[tuple[Path, str]]":
    return [(CONSTANTS_PY, build_constants(reg)), (OBS_SPEC_JSON, build_obs_spec(reg))]


def emit(reg: dict) -> "list[Path]":
    written = []
    for path, text in _targets(reg):
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def check_generated(reg: dict) -> "list[str]":
    """Regenerate in-memory; return a problem per generated file that differs from / is missing on disk."""
    problems: "list[str]" = []
    for path, text in _targets(reg):
        if not path.exists():
            problems.append(f"{path.relative_to(REPO_ROOT)}: missing (run the generator)")
        elif path.read_text(encoding="utf-8") != text:
            problems.append(f"{path.relative_to(REPO_ROOT)}: STALE — regenerate (python scripts/generate_from_registry.py)")
    return problems


def all_validations(reg: dict) -> "dict[str, list[str]]":
    return {
        "schema_sources": validate_schema_sources(reg),
        "norm_keys": validate_norm_keys(reg),
        "dataset_spec": validate_dataset_spec(reg),
        "layout_coverage": validate_layout_channel_coverage(reg),
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="write nothing; assert zero-diff + run validations")
    args = ap.parse_args(argv)

    reg = load_registry()
    failures: "list[str]" = []

    if args.check:
        failures += check_generated(reg)
    else:
        for p in emit(reg):
            print(f"wrote {p.relative_to(REPO_ROOT)}")
        # after emit, a check must be clean (proves determinism of the just-written files)
        failures += check_generated(reg)

    for label, probs in all_validations(reg).items():
        for p in probs:
            failures.append(f"[{label}] {p}")

    if failures:
        print("FAIL:", file=sys.stderr)
        for f in failures:
            print(f"  - {f}", file=sys.stderr)
        return 1
    print("registry generate + validate: OK"
          f" (constants + obs_spec fresh; schema/norm/dataset_spec linkage valid)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
